# Generated by Django 2.2.7 on 2022-03-04 09:59

from django.db import migrations
import key_management.models


class Migration(migrations.Migration):

    dependencies = [
        ('key_management', '0003_user'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', key_management.models.UserManager()),
            ],
        ),
    ]
